# Plugins
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh
zplug "zsh-users/zsh-autosuggestions"
zplug "plugins/git", from:oh-my-zsh
zplug "zdharma/fast-syntax-highlighting", defer:3
zplug "zsh-users/zsh-completions"
zplug "Aloxaf/fzf-tab"

# Install plugins if there are plugins that have not been installed
if ! zplug check; then
   zplug install
fi

# Load everything
zplug load

# Global exports
export TERM="xterm-256color"
export PATH="/usr/local/opt/qt@5.5/bin:/usr/local/bin:$HOME/bin:$HOME/usr/local/bin:/Users/phillipmuldoon/.cask/bin:$PATH"
export NVM_DIR="$HOME/.nvm"

# Direnv hooks
export DIRENV_LOG_FORMAT=  # comment this out to be more verbose
eval "$(direnv hook zsh)"

# History config
alias hh=hstr                    # hh to be alias for hstr
export HISTFILE=~/.zsh_history   # ensure history file visibility
export HSTR_CONFIG=hicolor       # get more colors
bindkey -s "\C-r" "\eqhstr\n"    

# Setup the editor
alias emacs="/usr/local/opt/emacs-plus/Emacs.app/Contents/MacOS/Emacs"
export EDITOR=emacs
export VISUAL=$EDITOR

# Various Rails shortcuts
alias rsp='bundle exec rspec'
alias rke='bundle exec rails'

# bat > cat
alias cat='bat'
alias ls='ls -G'

# FZF setup
# FZF defaults
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_DEFAULT_OPTS="--bind='ctrl-o:execute(emacs {})+abort'
--color=dark
--color=fg:-1,bg:-1,hl:#5fff87,fg+:-1,bg+:-1,hl+:#ffaf5f
--color=info:#af87ff,prompt:#5fff87,pointer:#ff87d7,marker:#ff87d7,spinner:#ff87d7" 

# FZF completion
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_COMPLETION_TRIGGER=''
bindkey '^T' fzf-completion
bindkey '^I' $fzf_default_completion

# Lazily load ZSH functions.
fpath=($fpath ~/autoloaded)
autoload fpreview fif fkill fbrewi fbrewu fbrewd

# preview - fuzzy open with emacs from anywhere
# ex: preview word1 word2 ... (even part of a file name)
fpreview() {
  # undefined
	builtin autoload -X
}

# fif - Find in file and open it.
fif() {
  # undefined
	builtin autoload -X
}

# fkill - Kill processes - list only processes user can kill.
fkill() {
  # undefined
	builtin autoload -X
}

# fbrewi - Install (one or multiple) selected application(s)
# using "brew search" as source input
fbrewi() {
  # undefined
	builtin autoload -X
}

# fbrewu - Update (one or multiple) selected application(s)
fbrewu() {
  # undefined
	builtin autoload -X
}

# fbrewd - elete (one or multiple) selected application(s)
fbrewd() {
  # undefined
	builtin autoload -X
}

# Set mouse scaling
defaults write -g com.apple.mouse.scaling  6.0

# VPN CLI
alias favpn="osascript -e 'tell application \"Viscosity\" to connect \"Corporate VPN V3.0\"'"

# We don't go to Ravenholm^H^H^H^HSpring
#export DISABLE_SPRING=true

# Setup AWS
export AWS_VAULT_KEYCHAIN_NAME=login

# Increase number of open files to appease chromedriver
ulimit -n 2056

# Prompt (must go last in this file)
eval "$(starship init zsh)"
